M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu18.04.1} date Wed 01 Jan 2025 16:08:21 ACDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-01T16:08:21+10:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu18.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.25Y-4.7
X3.25Y-5.15
X4.547Y-4.7
X4.547Y-5.15
T0
M30
